services:
  backend:
    build: ./backend
    container_name: editorai-backend
    command: [php, artisan, serve, --host=0.0.0.0, --port=8000]
    volumes:
      - storage-data:/var/www/storage/app/public
      - backend-db:/var/www/database
    env_file:
      - ./backend/.env
    networks:
      - editorai

  frontend:
    build: ./frontend
    container_name: editorai-frontend
    ports:
      - "2994:80"
    depends_on:
      - backend
    networks:
      - editorai

volumes:
  storage-data:
  backend-db:


networks:
  editorai:
    driver: bridge
