<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $appName }} · Tural account</title>
<style>body{font:16px system-ui,sans-serif;background:#11131b;color:#edf0ff;margin:0;min-height:100vh;display:grid;place-items:center}.card{box-sizing:border-box;width:min(484px,calc(100vw - 32px));padding:32px;background:#1c202c;border:1px solid #383e50;border-radius:18px}h1{font-size:26px;margin:0 0 12px}p{line-height:1.6;color:#bfc6d8}a{color:#aabfff}button,.primary{display:block;box-sizing:border-box;width:100%;padding:14px;border:0;border-radius:9px;background:#5278ec;color:white;font:inherit;text-align:center;text-decoration:none;cursor:pointer;margin-top:16px}input[type=password],input[type=text]{box-sizing:border-box;width:100%;padding:12px;margin:8px 0 16px;border:1px solid #485168;border-radius:8px;background:#10131e;color:white;font:inherit}label{line-height:1.5}.secondary{background:#343d53}details{margin:24px 0 0}#error{color:#ffb6b6}small{display:block;margin-top:18px;color:#a2adc3}</style></head>
<body><main class="card">
@if($mode === 'login')
<h1>Sign in to {{ $appName }}</h1><p>Use your Tural account to continue.</p>
@if($sharedEnabled ?? true)<a class="primary" href="/api/auth/sso/start">Continue with Tural</a>@endif
<details><summary>Link an existing {{ $appName }} account</summary><p>Keep your existing projects and access. Confirm your application password, then sign in to your Tural account. You need an existing application session in this browser.</p>
<form id="link-form">@csrf<label>Application password<input type="password" name="password" autocomplete="current-password" required></label><label><input type="checkbox" name="confirm_link" required> Link my existing application account to the Tural account I sign in to next.</label><button>Confirm and continue</button></form><p id="error" role="alert"></p></details>
<script>
document.getElementById('link-form').addEventListener('submit',async function(event){event.preventDefault();const error=document.getElementById('error');error.textContent='';let token=null;try {token=localStorage.getItem('auth_token');}catch{}if(!token){error.textContent='An existing application session is required. Link the account before switching sign-in, or contact your account owner.';return;}const form=new FormData(this);try {const response=await fetch('/api/auth/sso/link',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','Authorization':'Bearer '+token,'X-CSRF-TOKEN':form.get('_token')},body:JSON.stringify({password:form.get('password'),confirm_link:form.get('confirm_link')==='on'})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Account link could not be confirmed.');window.location.assign(result.authorization_url);}catch(e){error.textContent=e.message||'Sign-in is unavailable.';}});
</script>
@elseif($mode === 'onboard')
<h1>Create your {{ $appName }} account</h1><p>Your Tural account is verified. Creating an application account gives you a new workspace; existing projects require account linking.</p>
<p>{{ $email }}</p><form method="post" action="/api/auth/sso/onboard">@csrf<label>Your name<input type="text" name="name" maxlength="255" autocomplete="name" required></label><label><input type="checkbox" name="confirm_create" value="1" required> Create my application account.</label><button>Create account</button></form><a href="/api/auth/sso/login">Link an existing account instead</a>
@elseif($mode === 'account')
<h1>{{ $appName }} account</h1><p>Signed in as {{ $userName }}.</p><form method="post" action="/api/auth/sso/logout">@csrf<input type="hidden" name="scope" value="local"><button>Sign out of this app</button></form><form method="post" action="/api/auth/sso/logout">@csrf<input type="hidden" name="scope" value="global"><button class="secondary">Sign out of all Tural apps</button></form><small>Shared sign-out ends access in connected apps when they next verify the session.</small><a href="/">Return to {{ $appName }}</a>
@endif
</main></body></html>
